sudo: required
language: node_js
node_js:
  - "node"
services:
  - postgresql 
before_script:
  - npm install
  - npm install coveralls --save-dev
  - npm install mocha-lcov-reporter --save-dev
  - npm install supertest 
  - yarn global add nyc
script:
  - npm test
  - nyc --reporter=lcov npm test

after_success:
  - npm run coveralls